### ISSUE TITLE
Release PSK v3.1.0

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#1038]
## PSK v3.1.0 (Polymer v2)

- [x] Release PSK `v2.2.0`. #1035
- [x] Move to relative paths with a `<base>` tag and `Polymer.rootPath`.
- [x] Update build section in the README. #1034
- [x] Merge `2.0-preview` in `master`. #1027
- [x] Tag new version.

### Possible features to add in this version

- [ ] **(?)** Remove unneeded properties. #1037
- [ ] **(?)** Implement `lazy-imports`. #998

After that, we need to update the Polymer CLI with the new tagged version?

**Comment by FluorescentHallucinogen** [comment]
Any updates?

**Comment by abdonrd** [comment]
For now, waiting for the PRs...

**Comment by abdonrd** [comment]
[Released Polymer Starter Kit v3.1.0](https://github.com/PolymerElements/polymer-starter-kit/releases/tag/v3.1.0)! 🎉

**Comment by stramel** [comment]
Dang... Wish lazy-imports could have shipped.... :disappointed:
