### ISSUE TITLE
Release PSK v3.2.0

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#1068]
## Changelog

- [x] Cache the polyfills in runtime & cache images. #1035
- [x] Remove unneeded `bower.json` from `polymer.json`. https://github.com/PolymerElements/polymer-starter-kit/commit/b8d74a5904101c39cf53e9ae5bb7bb6b47ca5b6e
- [x] Update `manifest.json`. #1067
- [ ] Tag new version. [Draft release](https://github.com/PolymerElements/polymer-starter-kit/releases/tag/untagged-5d8307f80548ff2984b1)

## Comparing changes from last version

https://github.com/PolymerElements/polymer-starter-kit/compare/v3.1.0...master

## Pending features for futures versions (?)

- [ ] Remove unneeded properties. #1037
- [ ] Implement `lazy-imports`. #998

**Comment by keanulee** [comment]
Released!

**Comment by abdonrd** [comment]
Thanks for the review @keanulee!
