### ISSUE TITLE
🍭 gulp / build issue tracker

### ISSUE THREAD

**Issue by samccone** [PolymerElements/polymer-starter-kit#382]
* [x] https://github.com/PolymerElements/polymer-starter-kit/issues/381
* [x] https://github.com/PolymerElements/polymer-starter-kit/issues/373
* [x] https://github.com/PolymerElements/polymer-starter-kit/issues/375  -- (pending PR https://github.com/PolymerElements/polymer-starter-kit/pull/384)
* [x] https://github.com/PolymerElements/polymer-starter-kit/issues/289  -- (pending PR https://github.com/PolymerElements/polymer-starter-kit/pull/385)
* [x] https://github.com/PolymerElements/polymer-starter-kit/issues/323
* [x] https://github.com/PolymerElements/polymer-starter-kit/issues/225 -- (pending PR https://github.com/PolymerElements/polymer-starter-kit/pull/386)
* [x] https://github.com/PolymerElements/polymer-starter-kit/pull/370 :white_check_mark:

**Comment by samccone** [comment]
👍👍👍👍👍

**Comment by addyosmani** [comment]
That was fast!

**Comment by samccone** [comment]
:racehorse:
